// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1QAHCsYBiaemuyHNTB2DAEKN3yZPQoAI',
    appId: '1:890138244201:web:d52bcb500e43737827def8',
    messagingSenderId: '890138244201',
    projectId: 'ekissan-f8cbc',
    authDomain: 'ekissan-f8cbc.firebaseapp.com',
    storageBucket: 'ekissan-f8cbc.appspot.com',
    measurementId: 'G-QBRSMYCRDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACbMoilGGWZnww5C1gw3Epab1Ls94gsMs',
    appId: '1:890138244201:android:fce6d7144596260327def8',
    messagingSenderId: '890138244201',
    projectId: 'ekissan-f8cbc',
    storageBucket: 'ekissan-f8cbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyt7LH_ysILQo4BTARlrkcLAU1tQhtXHE',
    appId: '1:890138244201:ios:11b2d47f6d97c4c027def8',
    messagingSenderId: '890138244201',
    projectId: 'ekissan-f8cbc',
    storageBucket: 'ekissan-f8cbc.appspot.com',
    androidClientId: '890138244201-ne7eno4pjc79sgdam0pfc8lifs9l0t04.apps.googleusercontent.com',
    iosClientId: '890138244201-vcht7fdrhbthdcm45ri1aljg822cstq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ekissanadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyt7LH_ysILQo4BTARlrkcLAU1tQhtXHE',
    appId: '1:890138244201:ios:c8ece8f333b7d35a27def8',
    messagingSenderId: '890138244201',
    projectId: 'ekissan-f8cbc',
    storageBucket: 'ekissan-f8cbc.appspot.com',
    androidClientId: '890138244201-ne7eno4pjc79sgdam0pfc8lifs9l0t04.apps.googleusercontent.com',
    iosClientId: '890138244201-0mq76ngnnnfiit5981bmling7sjhsj45.apps.googleusercontent.com',
    iosBundleId: 'com.example.ekissanadmin.RunnerTests',
  );
}
